### ISSUE TITLE
Fix the Checklist on Gutenberg

### ISSUE THREAD

**Issue by andergmartins** [AllediaWordPress/PublishPress#331]
## Useful links

https://riad.blog/2018/06/07/efficient-client-data-management-for-wordpress-plugins/
https://github.com/WordPress/gutenberg/issues/12692
https://riad.blog/2017/10/16/one-thousand-and-one-way-to-extend-gutenberg-today/
https://wordpress.org/gutenberg/handbook/designers-developers/developers/data/data-core-editor/
https://github.com/WordPress/gutenberg/issues/10992
https://stackoverflow.com/questions/48206998/gutenberg-editor-content-in-javascript-wordpress

## Requirements to fix

- [x]  Excerpt has text
- [x] Number of Categories
- [x] Number of Tags
- [x] Number of Words
- [x] Featured Image
- [x] Warning
- [x] Prevent saving
